### PR TITLE
binwalk: deps: build srecord from source

### PR DESCRIPTION
**Pull request by 0xXA**

### CODE REVIEW

**Comment by 0xXA** [comment]
You can check changes in 1.58 vs 1.64
And I think that may be enough reason for you to build it from source
http://srecord.sourceforge.net

**Comment by E3V3A** [comment]
The disadvantage is that srecord need a surprisingly large set of dependencies. Some of which are rather old/outdated from a development perspective. I recently compiled this, and it took a surprisingly long time to complete. 

I wish people would stop wanking around by using that 2000-era type of repo (sourceforge) and move their development to github so people actually **can** contribute. (But then again srec is from '98 so no wonder.)

Anyway, IMO it would have been much better if srecord could just provide a few updated pre-compiled binaries.

**Comment by 0xXA** [comment]
Well not "much" dependencies,
Are you building with libgcrypt ?

**Comment by E3V3A** [comment]
I don't remember, but I think yes. 
I do remember that something was dependent on about 40 different versions of the same library... maybe `newX.x.x`...

**Comment by 0xXA** [comment]
Building without libgcrypt will not bother anyone

**Comment by 0xXA** [comment]
Needs some work will be posting a new pull off it soon

**Pull request closed without merging**
