### PR TITLE
long and xrange() were removed from Python on 1/1/2020

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by akx** [comment]
This project is still compatible with Python 2. As far as I'm aware, there weren't retroactive changes to Python 2.7 on 2020-01-01.

**Comment by cclauss** [comment]
Python 2.7 died on 1/1/2020.

**Comment by akx** [comment]
Upstream support for Python 2.7 ended then, yes, but it didn't die. 

That said, I'm all for Python 3+ only, but that's what's happening in #488 ("drop python2 support").

**Comment by devttys0** [comment]
#488 has been merged, which addresses this

**Pull request closed without merging**
